In [35]:
import numpy as np
import statsmodels.tsa.vector_ar.svar_model as svar
import pandas as pd

In [36]:
df = pd.read_csv("test_data.csv")

In [41]:
df.iloc[:, 1:4]

SCU          ZCF          SAL
0      996.753421  1003.170356   998.269699
1     1001.293784  1007.682154  1014.257589
2      982.139811  1009.394196  1007.667311
3      996.690881  1006.246852  1009.591429
4      985.364314  1001.082492  1004.444957
5      980.535727  1000.985889  1011.221115
6      978.590794   999.121026  1010.768766
7      984.983083  1008.509892  1012.951237
8      980.623953  1002.127934  1024.336438
9      969.117332  1007.499176  1020.349449
10     970.802652  1012.042233  1025.382236
11     969.865273  1011.628553  1023.320565
12     964.569188  1010.066521  1024.617134
13     966.234352  1010.669043  1028.906386
14     939.008429  1007.866267  1023.751861
15     909.460872  1013.890002  1010.537217
16     916.198757  1013.387144  1018.082635
17     920.094016  1010.822803  1023.175862
18     920.692583  1009.459086  1028.469383
19     932.455936  1007.905140  1038.532440
20     930.206000  1012.849201  1038.171453
21     890.165597  1003.281723   998.923092
22     853.192334  1005.150478  1010.193503
23     815.617787  1005.274114   983.634127
24     827.966303  1003.404309  1000.447120
25     849.202685  1002.538776  1012.049409
26     852.740894  1001.554464  1006.600815
27     841.932419   984.483204  1004.788232
28     843.638645   988.109623  1007.899770
29     809.707083   985.165644   993.765650
...           ...          ...          ...
2731   999.332873  1016.736601   579.119374
2732   994.890545  1013.403270   578.833737
2733   979.988209  1013.667085   580.596111
2734   974.792327  1016.964479   582.800335
2735   975.786999  1012.464414   580.948724
2736   968.219432  1024.712649   575.871687
2737   977.298032  1028.906152   581.459478
2738   974.405076  1016.033162   574.504403
2739   966.514415  1010.578724   573.234076
2740   950.696391  1017.522559   567.037745
2741   964.857681  1007.748347   566.539959
2742   961.187081  1006.364619   558.139356
2743   971.785941  1002.389586   562.284046
2744   968.301232  1002.601198   563.554986
2745   968.301211   998.205945   563.703824
2746   955.084719   997.602517   562.224686
2747   955.310739   997.699932   563.719741
2748   939.605885  1003.902460   561.032340
2749   951.087083  1007.204806   562.691553
2750   930.087375  1001.089255   554.312519
2751   908.984656  1002.916732   552.079447
2752   921.163198  1002.401820   556.511502
2753   914.272560   990.401747   553.234516
2754   925.652610   987.876481   556.315835
2755   931.832657   992.024729   554.505876
2756   935.762229   989.453530   563.110001
2757   934.936502   988.204139   566.703847
2758   933.132523   987.151497   563.600897
2759   939.578181   989.673339   571.611850
2760   946.248153   990.854103   574.616601

[2761 rows x 3 columns]

In [60]:
sv = svar.SVAR(df.iloc[:, 1:4].values, svar_type='A', A=np.array(([1, 'e', 'e'], [0, 1, 'e'], [0, 0, 1])).T)

In [61]:
np.array(([1, 'e', 'e'], [0, 1, 'e'], [0, 0, 1]))

array([['1', 'e', 'e'],
       ['0', '1', 'e'],
       ['0', '0', '1']], dtype='|S11')

In [63]:
result = sv.fit()

In [64]:
dir(result)

['A',
 'A_mask',
 'A_solve',
 'B',
 'B_mask',
 'B_solve',
 '__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_bmat_forc_cov',
 '_char_mat',
 '_chol_sigma_u',
 '_cov_alpha',
 '_cov_sigma',
 '_forecast_vars',
 '_model_type',
 '_omega_forc_cov',
 '_zz',
 'acf',
 'acorr',
 'aic',
 'bic',
 'bse',
 'coefs',
 'cov_params',
 'cov_ybar',
 'dates',
 'detomega',
 'df_model',
 'df_resid',
 'endog',
 'endog_lagged',
 'exog_names',
 'fevd',
 'fittedvalues',
 'forecast',
 'forecast_cov',
 'forecast_interval',
 'fpe',
 'get_eq_index',
 'hqic',
 'info_criteria',
 'intercept',
 'irf',
 'irf_errband_mc',
 'irf_resim',
 'is_stable',
 'k_ar',
 'k_trend',
 'llf',
 'long_run_effects',
 'ma_rep',
 'mean',
 'model',
 'mse',
 'n_totobs',
 'names',
 'neqs',
 'nobs',
 'orth_ma_rep',
 'params',
 '

In [73]:
rirf = result.irf()

In [78]:
result.long_run_effects()

array([[ 136.2326591 ,  279.19060015,   22.75189861],
       [ 228.77457736,  418.75104959, -435.22533762],
       [-226.26194906,  180.59371138,  715.83511762]])

In [6]:
a = np.array([1, 2, 1])
b = np.array([1, 2, 3])

In [12]:
t = np.logical_or(a == 1, b == 1)

In [16]:
tnum = np.zeros_like(t, dtype=float)
tnum[~t] = A[~A_mask]
Anum[A_mask] = np.nan

array([False,  True, False])

In [18]:
np.identity((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])