In [6]:
import pandas as pd
from statsmodels.tsa.vector_ar import var_model as sm

In [7]:
data = pd.read_csv("test_data.csv", index_col=0)

In [8]:
data

SRB       DXI       DXJ       DJM
20131021 -0.000434 -0.008156  0.011227  0.004048
20131022  0.000014 -0.011891  0.001707 -0.004069
20131023 -0.001634 -0.011988 -0.008538 -0.015198
20131024 -0.008105 -0.016249 -0.013685 -0.014487
20131025 -0.003566 -0.001081 -0.009383 -0.004139
20131028 -0.005678 -0.005801 -0.008895 -0.002941
20131029  0.000300 -0.005194 -0.003789 -0.011121
20131030  0.006575  0.005328  0.008661  0.004454
20131031  0.003287  0.000709 -0.002006 -0.004138
20131101  0.006429  0.020411  0.003651 -0.003006
20131104  0.002526  0.007415 -0.001230 -0.010097
20131105 -0.000990 -0.002035 -0.008206 -0.005848
20131106 -0.003689 -0.001956  0.000430  0.005841
20131107  0.005581 -0.001060 -0.000352  0.002658
20131108  0.001210 -0.003895 -0.006698  0.000472
20131111 -0.004109 -0.002269 -0.005951 -0.007908
20131112  0.002918  0.001348  0.003950  0.003961
20131113 -0.002148  0.006901  0.007938  0.003297
20131114 -0.008549 -0.006379  0.004265  0.000978
20131115 -0.003702 -0.005348 -0.002303 -0.002574
20131118 -0.004678 -0.004702 -0.001179 -0.001984
20131119  0.002639  0.005849  0.006286  0.001160
20131120  0.008379  0.006558  0.011196  0.010037
20131121 -0.003573 -0.007322 -0.005304 -0.004031
20131122 -0.000279 -0.003060  0.001273 -0.003488
20131125  0.001748 -0.000167 -0.001459 -0.002781
20131126  0.007279  0.007658  0.005051  0.000983
20131127 -0.000809 -0.003208 -0.005282 -0.010993
20131128  0.003334  0.001070  0.003142  0.006606
20131129  0.000491  0.003956 -0.000333 -0.002385
...            ...       ...       ...       ...
20180312 -0.006917 -0.021667 -0.021806 -0.019946
20180313 -0.003433 -0.003402 -0.015582 -0.021808
20180314 -0.002348  0.010553 -0.005719  0.001491
20180315  0.008961  0.009225  0.002117  0.016375
20180316 -0.004696 -0.010182 -0.002643 -0.000434
20180319 -0.017219 -0.028481 -0.016222 -0.005774
20180320 -0.014498 -0.024448 -0.010888  0.001127
20180321  0.001479  0.005345  0.007500  0.010609
20180322 -0.005047  0.005315  0.002481 -0.010599
20180323 -0.045872 -0.042895 -0.036246 -0.036659
20180326 -0.028137 -0.016353 -0.020012  0.002089
20180327  0.008761  0.009122 -0.002594  0.007478
20180328  0.005738 -0.011280 -0.028562 -0.015246
20180329  0.003928  0.000953 -0.016899 -0.017613
20180330  0.022036  0.010350  0.019077  0.035532
20180402  0.018257  0.019452  0.037653  0.022853
20180403 -0.003167 -0.007963 -0.002517 -0.002694
20180404 -0.004741 -0.022376  0.006459  0.004901
20180409  0.005747 -0.016740 -0.015600 -0.011348
20180410  0.015179  0.024209  0.012027  0.008996
20180411  0.001405  0.007234 -0.006644 -0.002504
20180412 -0.006402 -0.014620 -0.030093 -0.027466
20180413  0.007290  0.004309  0.004178 -0.000384
20180416 -0.004660 -0.009409  0.011197 -0.006555
20180417 -0.004059 -0.013009  0.001342 -0.003841
20180418  0.016070  0.013420  0.034100  0.024176
20180419  0.012975  0.042416  0.019557  0.009892
20180420 -0.004832  0.003996 -0.006261 -0.007338
20180423  0.010089  0.010178  0.016332  0.001374
20180424  0.015341  0.007103  0.022636  0.023816

[1103 rows x 4 columns]

In [10]:
var = sm.VAR(endog=data.values)

In [11]:
result = var.fit()

E:\Anaconda2\lib\site-packages\statsmodels\tsa\vector_ar\var_model.py:461: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  params = np.linalg.lstsq(z, y_sample)[0]


In [17]:
dir(result)

['__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_bmat_forc_cov',
 '_char_mat',
 '_chol_sigma_u',
 '_cov_alpha',
 '_cov_sigma',
 '_forecast_vars',
 '_model_type',
 '_omega_forc_cov',
 '_zz',
 'acf',
 'acorr',
 'aic',
 'bic',
 'bse',
 'coefs',
 'cov_params',
 'cov_ybar',
 'dates',
 'detomega',
 'df_model',
 'df_resid',
 'endog',
 'endog_lagged',
 'exog_names',
 'fevd',
 'fittedvalues',
 'forecast',
 'forecast_cov',
 'forecast_interval',
 'fpe',
 'get_eq_index',
 'hqic',
 'info_criteria',
 'intercept',
 'irf',
 'irf_errband_mc',
 'irf_resim',
 'is_stable',
 'k_ar',
 'k_trend',
 'llf',
 'long_run_effects',
 'ma_rep',
 'mean',
 'model',
 'mse',
 'n_totobs',
 'names',
 'neqs',
 'nobs',
 'orth_ma_rep',
 'params',
 'plot',
 'plot_acorr',
 'plot_forecast',
 'plot_sample_acor

In [21]:
result.stderr?

Type:            ndarray
String form:    
[[0.00039027 0.00050565 0.00045187 0.0004542 ]
           [0.05322974 0.06896704 0.06163226 0.06194937]
           [0 <...> 7]
           [0.05484083 0.07105445 0.06349767 0.06382438]
           [0.04949549 0.06412877 0.05730855 0.05760341]]
Length:          5
File:            e:\anaconda2\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an a